# Generated by Django 5.0.4 on 2024-05-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_gymaddress_gym_name_gym_address"),
        ("users", "0005_employee_alter_user_role_employeeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="base_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.basecompany",
            ),
        ),
    ]
