# Generated by Django 5.0.4 on 2024-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_employeeprofile_base_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="salary",
            field=models.FloatField(default=0),
        ),
    ]
