# Generated by Django 5.0.4 on 2024-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_gymaddress_gym_name_gym_address"),
        ("users", "0007_employeeprofile_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="gyms",
            field=models.ManyToManyField(
                null=True, related_name="allowed_employees", to="crm.gym"
            ),
        ),
    ]
