# Generated by Django 5.0.4 on 2024-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
