# Generated by Django 5.0.4 on 2024-05-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_ticket_ticket_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketEntrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entrance_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrances",
                        to="users.ticket",
                    ),
                ),
            ],
        ),
    ]
