# Generated by Django 5.0.4 on 2024-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_services"),
        ("users", "0011_ticketentrance"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="favorites_gyms",
            field=models.ManyToManyField(
                blank=True, related_name="favorites_gyms", to="crm.gym"
            ),
        ),
    ]
