# Generated by Django 5.0.4 on 2024-05-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_ratingresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingresponse",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_responses",
                to="interactions.ratingresponse",
            ),
        ),
    ]
