# Generated by Django 5.0.4 on 2024-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_tickettempcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettempcode",
            name="ticket_type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
