# Generated by Django 5.0.4 on 2024-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_tickettempcode_ticket_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettempcode",
            name="ticket_type",
        ),
        migrations.AddField(
            model_name="tickettempcode",
            name="ticket_id",
            field=models.IntegerField(null=True),
        ),
    ]
