# Generated by Django 5.0.4 on 2024-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0008_agreement_newsletteragree_promotionsagree"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
