# Generated by Django 5.0.4 on 2024-06-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_services"),
        ("interactions", "0011_remove_userpushmessage_push_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="gym",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camapaigns",
                to="crm.gym",
            ),
        ),
    ]
