# Generated by Django 5.0.4 on 2024-06-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0012_campaign_gym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_notifications",
                to="interactions.campaign",
            ),
        ),
    ]
