# Generated by Django 5.0.4 on 2024-05-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseAddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_l1", models.CharField(max_length=250)),
                ("address_l2", models.CharField(blank=True, max_length=250, null=True)),
                ("city", models.CharField(max_length=250)),
                ("zip_code", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=50, null=True)),
                ("phone_nr", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseCompanyAddress",
            fields=[
                (
                    "baseaddressmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crm.baseaddressmodel",
                    ),
                ),
            ],
            bases=("crm.baseaddressmodel",),
        ),
        migrations.CreateModel(
            name="BaseCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.basecompanyaddress",
                    ),
                ),
            ],
        ),
    ]
