# Generated by Django 5.0.4 on 2024-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecompany",
            name="vat_id",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
