# Generated by Django 5.0.4 on 2024-05-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_gym"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymAddress",
            fields=[
                (
                    "baseaddressmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crm.baseaddressmodel",
                    ),
                ),
            ],
            bases=("crm.baseaddressmodel",),
        ),
        migrations.AddField(
            model_name="gym",
            name="name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.gymaddress",
            ),
        ),
    ]
