# Generated by Django 5.0.4 on 2024-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_gymaddress_gym_name_gym_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gym_images/"),
        ),
        migrations.AddField(
            model_name="gym",
            name="opening_time_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="opening_time_to",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
