# Generated by Django 5.0.4 on 2024-05-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_gym_description_gym_image_gym_opening_time_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="crm.gym",
                    ),
                ),
            ],
        ),
    ]
